### ISSUE TITLE
Is it possible to mirror the screen?

### ISSUE THREAD

**Issue by OliveiraHermogenes** [alexballas/go2tv#51]
Hi, there.

In my university, we've got projectors caged to the ceiling which otherwise work, except that it is very cumbersome to get cables from there.

I've got one of those cheap "Anycast" HDMI dongles that can act as a DLNA/UPnP renderer and would like to use it, instead of a long HDMI cable, to share my screen with students during a lecture. Go2TV works great for casting videos, but I couldn't figure out a way to cast/mirror my screen. Tried piping ffmpeg's x11grab output, but that didn't work ("Broken pipe"). If I dump the screen to a WebM/VP8 file and give that to Go2TV, then mirroring starts (although with some delay), but then breaks off after a few seconds.

Is there an easy way to implement this, or could you give me some pointers as to how to get this working?

Thank you very much for your work!

**Comment by alexballas** [comment]
Hello!

I also tried last month to "trick" ffmpeg to cast my screen but with no luck. Didn't spend too much time on it however. When you dump the screen to a WebM file and pass that to Go2TV, it sees it as a complete video file and only casts the data that already recorded up to this point. Maybe if there was a mode that treated this file as a sequential stream of data rather than a seekable object, maybe we could cast the full thing, but still that would be a hack and the delay would be massive (as you also identified). 
Something like changing https://github.com/alexballas/go2tv/blob/main/httphandlers/httphandlers.go#L300 to a `io.Copy` when in screen casting mode? Just speculating, I would need to run some tests.

The standard way to cast / mirror your screen is with the Wifi Display / Miracast protocol which is an entirely different thing from the UPNP implementation in Go2TV.

I'm a linux user myself but I believe that Windows support wireless display / anycast natively.

**Comment by pataquets** [comment]
@OliveiraHermogenes VLC has a `screen://` input source you might find useful.

**Comment by alexballas** [comment]
I think the only proper solution to that would be to implement the chromecast protocol https://github.com/alexballas/go2tv/issues/38. Any other workarounds would not work properly since the  DLNA protocol is not really designed for that. Closing.

**Comment by alexballas** [comment]
Version v2.1.0 will include an RTMP server for Chromecast streaming (if you have ffmpeg installed). This means that you can point OBS or any other application and stream your content to Chromecast. Unfortunately this wont work with DLNA/UPnp devices.
